#!/bin/bash
set -e

echo "🔧 Nix Rebuild Workaround for Git Ownership Issue"
echo ""

# Method 1: Try setting the config and rebuilding
echo "Method 1: Setting Git safe.directory for root user..."
echo "Please run these commands:"
echo ""
echo "1. First, check if the safe directory is already set:"
echo "   sudo git config --global --get-all safe.directory | grep angelsnixconfig"
echo ""
echo "2. If not found, add it:"
echo "   sudo git config --global --add safe.directory /Users/angel/angelsnixconfig"
echo ""
echo "3. Verify it was added:"
echo "   sudo git config --global --get-all safe.directory"
echo ""
echo "4. Try rebuild again:"
echo "   sudo ./rebuild.sh"
echo ""
echo "---"
echo ""
echo "Method 2: Use path-based flake reference (if Method 1 fails):"
echo "   sudo darwin-rebuild switch --flake path:/Users/angel/angelsnixconfig#angel"
echo ""
echo "---"
echo ""
echo "Method 3: Temporarily change ownership (last resort):"
echo "   sudo chown -R root:wheel /Users/angel/angelsnixconfig"
echo "   sudo ./rebuild.sh"
echo "   sudo chown -R angel:staff /Users/angel/angelsnixconfig"
echo ""
echo "After successful rebuild, the HRM MCP server will be available in Claude Code!"